### ISSUE TITLE
Link to the extension's VSCode Marketplace href

### ISSUE THREAD

**Issue by vanderhoop** [gp-pereira/refactorex#1]
First of all, thanks for cooking this up! Given the extension is relatively new, I think adding the extension page (for ease of installation) to the repo's 'About' setting might be helpful. If you agree, here's the href: https://marketplace.visualstudio.com/items?itemName=gp-pereira.refatorex

**Comment by gp-pereira** [comment]
I added the href to the about page, many thanks. I'll added an "editors installation" section soon when i start porting it.
