### ISSUE TITLE
Feature request: Automatically prompt for a new name after an extraction

### ISSUE THREAD

**Issue by randycoulman** [gp-pereira/refactorex#17]
Thanks so much for this long-awaited tool! I'm going to open a few issues based on my early usage of RefactorEx, but please know that I'm extremely grateful for all of your work on this so far!

When I extract a function, variable, or constant, RefactorEx generates a name for the extracted element. I then have to manually invoke a `Rename` action in order to give the extracted element the correct name.

A really nice enhancement would be for RefactorEx to perform the extraction and then immediately prompt for the new name without additional user interaction.

An alternative approach would be to first prompt for the new name, then perform the extraction using the provided name instead of an automatically-generated name. This approach might also minimize any formatting changes caused by the auto-generated name (e.g. #4).

**Comment by gp-pereira** [comment]
Hi there, I'm glad you liked it! 

I thought that it wasn't possible to do something like that, but after digging the vscode API documentation, I manage to pull it off. It follows the approach of asking the new name first and then perform the extraction. This is the commit in case you want  to take a look 4b849b77ec78d185fed44d41b90fdd259f7f312e. It's already available in the vscode on v0.1.28. Give it a shot and let me know what you think.

I'll respond the other issues you've opened as I act upon them. I'm mostly focused on writing the project report for my uni but I couldn't get this enhancement out of my head after your issue, so thanks for opening it. 

Happy holidays!

**Comment by randycoulman** [comment]
@gp-pereira Thanks! I'll give it a try when I can.
