### ISSUE TITLE
references via `import` are not renamed

### ISSUE THREAD

**Issue by DGollings** [gp-pereira/refactorex#3]
first of all, thanks for this plugin, coming from Go I *really* missed the excellent refactor tools it has (due to being very strongly typed of course)

But noticed a minor bug just now, this still beats `search&replace`

Given
```elixir
defmodule Foo do
  def a() do
  end

  def uses_a() do
    a()
  end
end
```

renaming `a()` to `b()`

works as expected
```elixir
defmodule Foo do
  def b() do
  end

  def uses_a() do
    b()
  end
end
```

but given
```elixir
defmodule AnotherModule do
 import foo # imported foo.a(), but used as a()

  def also_uses_a() do
    a() # this not changed after a rename
  end
end
```

renaming `a()` to `b()` has no effect on line 5 ion module AnotherModule

**Comment by gp-pereira** [comment]
Hi, I'm glad you liked it! So, there is a warning on the [README.md](https://github.com/gp-pereira/refactorex?tab=readme-ov-file#function-rename-function) about how renaming functions and guards only affects the current file. I initially implemented it by redirecting to a new private function with the new name but I felt too clunky upon daily usage. For the initial scope of the project (my undergrad final project), I decided to implement it single file only but intend to work on multiples edit throughtout the code after delivering the project report

**Comment by gp-pereira** [comment]
Hi, I'm glad you liked it! So, there is a warning on the [README.md](https://github.com/gp-pereira/refactorex?tab=readme-ov-file#function-rename-function) about how renaming functions and guards only affects the current file but I can see how that may not be enough.

I initially implemented it by redirecting to a new private function with the new name but it felt too clunky upon daily usage. For the initial scope of the project (my undergrad final project), I decided to implement it single file only but intend to work on multiples edit throughtout the code after delivering the project report.

**Comment by DGollings** [comment]
Ah, I see the warning now. Was distracted by the excellent little videos you made, maybe add some color to the warning?

**Comment by gp-pereira** [comment]
That was an excellent idea, so I already change the warning's color to yellow. I'll close this issue for now but, as I said, we'll get to full codebase renames in the future
