### ISSUE TITLE
Unable to start because GenLsp not found

### ISSUE THREAD

**Issue by Hermanlangner** [gp-pereira/refactorex#7]
After installing it fails to start with the following error
```
[Info  - 14:52:45] Client is waiting server
[Info  - 14:52:45] 
[Info  - 14:52:46] Server started on port 59913
[Error - 14:52:46] Server not started: Error: Command failed: export MIX_ENV=prod && cd /Users/hermanlangner/.vscode/extensions/gp-pereira.refatorex-0.1.24/refactorex && elixir --sname undefined -S mix run --no-halt -e "Application.ensure_all_started(:refactorex)" -- --port 59913
    error: module GenLSP is not loaded and could not be found
    │
  2 │   use GenLSP
    │   ^^^^^^^^^^
    │
    └─ lib/refactorex.ex:2: Refactorex (module)


== Compilation error in file lib/refactorex.ex ==
** (CompileError) lib/refactorex.ex: cannot compile module Refactorex (errors have been logged)
    (elixir 1.17.0) expanding macro: Kernel.use/1
    lib/refactorex.ex:2: Refactorex (module)

[Error - 14:53:17] Refactorex client: couldn't create connection to server.
Error: Client could not connect to the server.
```

Is there something I need to do in addition? It's possible my asdf environment is being weird.

environment is 
```
elixir 1.17.0-otp-27
erlang 27.0
```

**Comment by kyleboe** [comment]
Seeing this as well. Will have to disable the extension until this is fixed.

I'm using homebrew-installed elixir.
```
Elixir 1.17.3 (compiled with Erlang/OTP 27)
```

**Comment by gp-pereira** [comment]
Hey guys, I've tried my best but couldn't reproduce the issue with the exact setup as yours. A few other people are having startup related problems on Elixir 1.17 as well but I still don't know how to solve it. I'll keep working on possible solutions

**Comment by kyleboe** [comment]
Ok interesting. I restarted my machine and it is working now. Not sure what the issue was. Thanks for the attempts to reproduce. If it happens again, I'll try and capture more context. Also, thanks for the awesome library!
